### ISSUE TITLE
SM64 Green Stars Pipe Crash on Interpreter and Pure Interpreter

### ISSUE THREAD

**Issue by summunkid** [mkdasher/mupen64-rr-lua-#112]
In Sm64 Green Stars, entering some pipes will crash the game unless you enter it on a specific corner of the pipe. Using Dynamic Recompiler instead of Interpreter or Pure Interpreter fixes this.

Download used is the link in this video (https://www.youtube.com/watch?v=vXapDMDTlvI) next to "Pre-Patched Download"
Pipes that work:
The Course 2 pipe
The pipe in the building where Course 3 is
The Bowser 1 pipe
The lowest pipe in Course 4
The pipe that leads to a single red coin in the metal cap course

**Comment by Madghostek** [comment]
I traced the crash to happen in sm64 source code [here](https://github.com/n64decomp/sm64/blob/66018e9f3caaa67399218971d61366cb3f7ba7d7/src/engine/surface_collision.c#L49) (luckily it wasn't custom romhack assembly), it has to do with the pipe wall normals, but I don't know yet why mupen cores behave differently, I will look into it further

**Comment by Madghostek** [comment]
So the reason dynamic recompiler doesn't crash is because by default it doesn't handle floating point crashes so well (compared to interpreted modes), but after enabling `Emulate float crashes` all cores show the same error about invalid operation. While it's not the best argument, project64 reports same error, so it's most likely the romhack to blame here (I haven't analysed why exactly it crashes because it would take ages)
