### ISSUE TITLE
Turning the statusbar on/off during emulation doesn't resize the screen properly until a reset

### ISSUE THREAD

**Issue by Wade7wastaken** [mkdasher/mupen64-rr-lua-#137]
**Describe the bug**
If the statusbar is off when emulation starts, and it is it turned on, the screen won't resized to include the statusbar, The statusbar ends up covering some of the bottom of the screen. Likewise, if the statusbar is on and is then turned off, extra space is left at the bottom. These issues are fixed when the emulator is reset.

**To Reproduce**
1. Start emulation with the status bar off
2. Turn the statusbar on

**Expected behavior**
The screen should be resized whenever the statusbar is toggled.

**Screenshots**
Incorrect:
![image](https://github.com/mkdasher/mupen64-rr-lua-/assets/86390605/aa8a26d3-218d-40b0-a542-906992d45da7)

Correct:
![image](https://github.com/mkdasher/mupen64-rr-lua-/assets/86390605/5667e735-eaad-46ce-8538-efa69351fcae)

**Comment by Aurumaker72** [comment]
This behaviour is caused by the Zilmar spec.

When emulation starts, the video plugin is provided with various handles and asked to size the window accordingly.

```cpp

gfx_info.hWnd = mainHWND;
gfx_info.hStatusBar = Config.is_statusbar_enabled ? statusbar_hwnd : nullptr;

initiateGFX(gfx_info);

````

However, this process is only performed at core startup. This means that any changes to dependent state (e.g.: statusbar being hidden) can't get picked up by video plugin.
