### ISSUE TITLE
m64 playback fails to press final input

### ISSUE THREAD

**Issue by EZGames69** [mkdasher/mupen64-rr-lua-#46]
This bug is very random and sometimes happens and sometimes doesn’t.  But basically whenever you’re playing a movie file, there’s a chance that the movie will close from the emulator before it even has a chance to press the last button.  This is very annoying to deal with especially if you are dumping something at high res for a very long time.  

One solution to this may be to have the movie stay active for a couple extra frames after the final input is made just to ensure it’s not missed, or implement some sort of “finished” state where the movie is still loaded, but it acknowledges that you reached the end, kinda like what bizhawk does.

This would save alot of the headaches with trying to dump video from Mupen and not being able to use the final part.

**Comment by EZGames69** [comment]
Here is a list of movies on TASVideos that I know have this issue:

https://tasvideos.org/2336M
https://tasvideos.org/2684M
https://tasvideos.org/1851M
https://tasvideos.org/975M

**Comment by Wade7wastaken** [comment]
I’ve experienced this too when I made my video plugin comparison (https://youtu.be/5r-4c41rOGU), but only with Angrylion RDP Plus. The other plugins always worked fine. I tested Angrylion twice more and it happened both times. I thought I’d share my findings because it’s a lot less random for me.

**Comment by CasualPokePlayer** [comment]
I believe this might just be due to VI count mismatches between playback and header (which can explain it occuring in Angrylion RDP Plus but other plugins seemed to work fine in Wade's case, Angrylion probably lags more than the other). So playback takes more VIs than the movie header reports to actually play back all the inputs. So simply slapping in a bullshit high VI count can workaround this. No need to add extra frames of input.

Maybe the movie should just continue playing regardless of VI count in header and only care about input count? VI count becomes problematic here anyways with all the different plugins around which can generate different levels of lag.

**Comment by Madghostek** [comment]
Fixed on dev branch, now movie doesn't stop when VI counter runs out, which differs from plugin to plugin (rsp)
